### ISSUE TITLE
상품/카테고리/옵션 Validation 체크

### ISSUE THREAD

**Issue by 0n1dev** [f-lab-edu/five-minutes-market#14]
상품/카테고리/옵션 Validation 체크

**Comment by beaniejoy** [comment]
- Product
  - `name`: 0 < 자릿수 < 256, (Not Blank, 빈 문자열 허용X)
  - `price`: 0보다 큰 정수 (혹시 최댓값이 필요하면 설정해도 좋을 것 같습니다.)
  - `quantity`: 0보다 큰 정수 (이것도 최댓값 필요하면 설정해도 좋을 것 같습니다.)
  - `thumb`:  ~ 256자리 String (Not Blank)
  - `detail`: 0 ~ 1024자리 String

- ProductOption
  - 대상 없음

- ProductOptionItem
  - `productOptionItemName`:  ~ 256자리 (Not Blank)
  -  `productOptionItemPrice`: 0보다 큰 정수 (최댓값 고려)

- MainCategory
  - `mainCategoryName`:  ~ 256자리 (Not Blank)
- SubCategory
  - `subCategoryName`:  ~ 256자리 (Not Blank)

전반적으로 범위에 대한 논의가 있어야 될 것 같습니다! 일단 위의 내용과 같이 임시로 설정은 해봤습니다.
