### ISSUE TITLE
유저 도메인 개발

### ISSUE THREAD

**Issue by 0n1dev** [f-lab-edu/five-minutes-market#15]
유저 도메인 개발

**Comment by beaniejoy** [comment]
User(or Member)
- user_id (식별자)
- user_name (닉네임)
- email
- password
- address
- phone_number
- registered_at (등록날짜시간)
- updated_at (수정날짜시간)
- member_role
관리자, 일반사용자(판매자, 구매자) 등 어떻게 role을 부여할지에 대해 논의 필요

일단 로그인, 회원가입에 대한 기능 구현이 우선이기 때문에 애매한 속성 빼고 개발 진행하고 있겠습니다.
논의가 필요해 보이는 부분은 role 영역입니다. 
보통은 관리자, 사용자 영역 나누는 용도로 사용되기도 하는데 저희는 추가로 판매자, 구매자에 대해서도 고민해봐야될 것 같습니다.

혹시 수정 필요해보이는 부분에 대해 있으면 말씀해주세요.

**Comment by 0n1dev** [comment]
이정도면 괜찮을것 같습니다.
판매자, 구매자 구분은 Role 정도로 구분하면 좋을것 같아요. 오픈마켓이니 판매자가 구매자가 될수도 있고, 구매자가 판매자가 될수있을거라고 생각이 드네요
