### ISSUE TITLE
Category, Option 예외 처리 로직

### ISSUE THREAD

**Issue by 0n1dev** [f-lab-edu/five-minutes-market#8]
Category, Option 예외 처리 로직

**Comment by beaniejoy** [comment]
- **MainCategory**
    - `MainCategoryNotExisted(NotFound)Exception`
    조회시 MainCategory 존재X, 주로 select by id에서 발생
    - `MainCategoryNameDuplicatedException`
    새로 입력할 카테고리 이름이 기존에 DB에 등록된 카테고리인 상황
- **SubCategory**
    - `SubCategoryNotExisted(NotFound)Exception`
    해당 SubCategory가 존재하지 않는 경우
    - `SubCategoryNameDuplicatedException`
    insert 상황에서 DB에 같은 이름의 SubCategory 존재하는 경우
    - `ParentCategoryNotExistedException`
    subCategory의 상위 category(mainCategory)가 존재하지 않는 경우
- **ProductOption**
    - `ProductOptionNotExisted(NotFound)Exception`
    해당 ProductOption이 존재하지 않는 경우
- **OptionItem**
    - `OptionItemNotExisted(NotFound)Exception`
    해당 OptionItem이 존재하지 않는 경우
    - `ProductOptionNotAssignedException`
    OptionItem이 속해있는 ProductOption을 할당받지 못한 경우

Exception 이름은 임시로 지정했는데 논의 후에 통일성있는 방향으로 가면 좋을 것 같네요.

**Comment by 0n1dev** [comment]
좋은 명칭인것 같습니다. NotFound로 할까요?

**Comment by beaniejoy** [comment]
NotFound 좋습니다! 😃
